Agrega os resultados de cada rota, formando a planilha final referente às rotas escolhidas

In [159]:
import pandas as pd
import os
from tqdm import tqdm

In [160]:
resultados_desag = os.listdir("resultados_desagregados")
df = pd.DataFrame()

for i in tqdm(resultados_desag):
    fhand = pd.read_csv("resultados_desagregados\\"+i) 
    df_hand = pd.DataFrame(fhand.iloc[len(fhand)-1, [3,6,8]]).T # Handler (DF) extraído do csv de cada rota
    df_hand["Rota"] = i.split(".")[0] # Rota_Viagem_id adicionado ao handler
    df = pd.concat([df, df_hand]) # Handler adicionado ao arquivo final
df = df.set_index("Rota")
df["Nível de Precipitação Total (mm)"] = df["Precip. Media Acum. (mm/h)"]*(df["Tempo de Viagem Acum. (s)"]/3600)

# Salvar os resultados
df.to_excel(r"resultados.xlsx")

100%|██████████████████████████████████████████████████████████████████████████████| 1763/1763 [00:36<00:00, 48.29it/s]

In [161]:
df

,Precip. Media Acum. (mm/h),Dist. Percorrida Acum. (Km),Tempo de Viagem Acum. (s),Nível de Precipitação Total (mm)
Rota,,,,
rota_100090042,76.397586,15.88189,1593.19,33.809964
rota_100421673,112.357378,27.44793,3620.91,113.009987
rota_100616023,57.240725,14.89112,1542.67,24.528764
rota_100806782,92.793736,34.31266,3145.25,81.072083
rota_100986304,10.902295,9.90877,854.22,2.586933
...,...,...,...,...
rota_9886818,15.016106,4.14777,446.59,1.86279
rota_99064556,97.280454,36.00018,2901.37,78.401831
rota_99136145,3.461489,9.64257,924.07,0.888516
rota_99361501,5.001037,21.09825,1802.83,2.50445
rota_99435878,79.237617,20.35624,3029.38,66.678014